// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCBEMGu3BjWxCnvRAo9nEA__O0f82pDdDc',
    appId: '1:922616978098:web:cc1e38f9e6795f7c3787ab',
    messagingSenderId: '922616978098',
    projectId: 'hendrix-arboretum',
    authDomain: 'hendrix-arboretum.firebaseapp.com',
    storageBucket: 'hendrix-arboretum.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCaH01rIO8gRoG7Q3AaGpQARASe7-Qup0s',
    appId: '1:922616978098:android:83e217e8347dc8a33787ab',
    messagingSenderId: '922616978098',
    projectId: 'hendrix-arboretum',
    storageBucket: 'hendrix-arboretum.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAkqjCFYu3DEnLty_cc7TZWT5LqqEmGEVA',
    appId: '1:922616978098:ios:d3b3a29cba2f35c63787ab',
    messagingSenderId: '922616978098',
    projectId: 'hendrix-arboretum',
    storageBucket: 'hendrix-arboretum.firebasestorage.app',
    iosBundleId: 'com.example.finalProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAkqjCFYu3DEnLty_cc7TZWT5LqqEmGEVA',
    appId: '1:922616978098:ios:d3b3a29cba2f35c63787ab',
    messagingSenderId: '922616978098',
    projectId: 'hendrix-arboretum',
    storageBucket: 'hendrix-arboretum.firebasestorage.app',
    iosBundleId: 'com.example.finalProject',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCBEMGu3BjWxCnvRAo9nEA__O0f82pDdDc',
    appId: '1:922616978098:web:5a727dc6956c61673787ab',
    messagingSenderId: '922616978098',
    projectId: 'hendrix-arboretum',
    authDomain: 'hendrix-arboretum.firebaseapp.com',
    storageBucket: 'hendrix-arboretum.firebasestorage.app',
  );
}
